// this is a BUN script
import * as cheerio from "cheerio";
import path from "path";
const innerHTML = await fetch("https://docs.ntfy.sh/emojis/").then((r) =>
  r.text(),
);
const $ = cheerio.load(innerHTML);
const els = $(".c");
let mapped: { label: string; value: string }[] = [];
els.each((i, el) => {
  if (!el.parent) return;
  const value = $(el).text();

  const label = $(el.parent.childNodes[1]).text().trim();
  mapped.push({ label, value });
});
console.log(mapped);
Bun.write(
  path.join(__dirname, "..", "src", "emojis.ts"),
  `/**\n Autogenerated file.\n extracted from docs.ntfy.sh/emojis\n **/\n\nexport default ${JSON.stringify(mapped, null, 4)}`,
);
console.log(`Wrote emojis`);
