name: Remote Deploy

on:
    push:
      branches:
        - main
      paths:
        # on code related change
        - ".github/workflows/deploy.yml"
        - "src/**"
        - "public/**"
    workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: 
        name: production
        url: https://saahild.com/ntfy-gen
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.WEB_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.WEB_PORT }}
          script: |
            PUBLIC_URL=/ntfy-gen bash ./deploy_project.sh ${{ github.event.repository.name }} ntfy-gen "npm install" "npm run build"